// Result type
export type Result<T> = Success<T> | Failure

type Success<T> = {
  success: true
  data: T
}

type Failure = {
  success: false
  error: {
    code: string
    message: string
    details?: unknown
  }
}

// Unified product (matches unified.json generated by build_db.py)
export type UnifiedProduct = {
  ec_hinban: string
  rakuten_code?: string
  yahoo_code?: string
  amazon_sku?: string
  asin?: string
  zaishitsu?: string
  hinban?: string
  color?: string
  size?: string
  tehai?: string
  /** EC 商品の幅（サイズ表記 "1080mm*1ｍ" から抽出） */
  haba_mm?: number
  cut_m?: number
  arari_rate?: number
  kotei_hi?: number
  hanbai_kakaku?: number
  shiire_changed_date?: string
  rakuten_price?: number
  rakuten_price_202605?: number
  yahoo_price?: number
  yahoo_price_202605?: number
  amazon_price?: number
  amazon_price_202605?: number
  amazon_hojin_price?: number
  shiire_per_m?: number
  nokori_m?: number
  zaiko_source?: string
  zaiko_haba_mm?: number
  meopen_um?: number
  mesh_count?: number
  senkei_um?: number
  kaikouritsu?: number
  zaiko_match?: string
  zaiko_status?: string
  /** 仕様（目開き・メッシュ数・線径）の出どころ: 在庫表 / Amazon商品名 / 品番 */
  spec_source?: string
  /** 横のメッシュ数・目開き・線径。スラッシュ表記「635/4300」の 2 つ目（縦/横であり下限/上限ではない）。
   *  空なら縦と同じか不明。縦の値は mesh_count / meopen_um / senkei_um */
  mesh_count_yoko?: number
  meopen_yoko_um?: number
  senkei_yoko_um?: number
  /** 濾過粒度 μm（畳織。商品名の「粒球子」） */
  roka_ryudo_um?: number
  /** 保管場所（2F / 3F 等）。紐づけの見出しなし列から仕入先と分けたもの */
  hokan_basho?: string
  /** 仕入先（表記ゆれを寄せた名前。複数社は「/」区切り） */
  shiiresaki?: string
}

// User-editable overrides stored in Firestore
export type ProductOverride = {
  shiire_per_m?: number
  kotei_hi?: number
  arari_rate?: number
  updated_at: string // ISO 8601
}

// Search filter
export type SearchFilter = {
  zaishitsu?: string
  /** 材質の複数選択（OR）。正規化した完全一致で照合する */
  zaishitsu_list?: string[]
  meopen_um_min?: number
  meopen_um_max?: number
  mesh_count_min?: number
  mesh_count_max?: number
  senkei_um_min?: number
  senkei_um_max?: number
  /** 横のメッシュ数・線径。商品に横の値が無ければ縦の値（正方目）と比べる */
  mesh_count_yoko_min?: number
  mesh_count_yoko_max?: number
  senkei_yoko_um_min?: number
  senkei_yoko_um_max?: number
  kaikouritsu_min?: number
  kaikouritsu_max?: number
  zaiko_haba_mm_min?: number
  zaiko_haba_mm_max?: number
  hinban?: string
  ec_hinban?: string
  color?: string
  freeText?: string
  /** 在庫状況（未指定 = 全件） */
  stockStatus?: 'in_stock' | 'direct_ship'
  /** 使用上限温度がこの値以上の素材のみ（特性データのある素材が対象） */
  heatMaxC_min?: number
  /** 耐酸性が◎の素材のみ */
  acidResistantOnly?: boolean
  /** 耐アルカリ性が◎の素材のみ */
  alkaliResistantOnly?: boolean
  /** 耐溶剤性が◎の素材のみ */
  solventResistantOnly?: boolean
}

// Sort
export type Sort = {
  field: 'hinban' | 'meopen_um' | 'mesh_count' | 'senkei_um' | 'kaikouritsu' | 'zaiko_haba_mm' | 'nokori_m' | 'shiire_per_m' | 'hanbai_kakaku' | 'ec_hinban' | 'zaishitsu'
  order: 'asc' | 'desc'
}

// SearchResult
export type SearchResult = {
  product: UnifiedProduct
  calculatedPrice: number | null
  overridden?: boolean // true if any field has a Firestore override
}

// Pagination
export type Pagination = {
  page: number
  pageSize: number
  totalResults: number
  totalPages: number
}
