// Result type
export type Result<T> = Success<T> | Failure

type Success<T> = {
  success: true
  data: T
}

type Failure = {
  success: false
  error: {
    code: string
    message: string
    details?: unknown
  }
}

// Unified product (matches unified.json generated by build_db.py)
export type UnifiedProduct = {
  ec_hinban: string
  rakuten_code?: string
  yahoo_code?: string
  amazon_sku?: string
  asin?: string
  zaishitsu?: string
  hinban?: string
  color?: string
  size?: string
  tehai?: string
  cut_m?: number
  arari_rate?: number
  kotei_hi?: number
  hanbai_kakaku?: number
  shiire_changed_date?: string
  rakuten_price?: number
  rakuten_price_202605?: number
  yahoo_price?: number
  yahoo_price_202605?: number
  amazon_price?: number
  amazon_price_202605?: number
  amazon_hojin_price?: number
  shiire_per_m?: number
  nokori_m?: number
  zaiko_source?: string
  zaiko_haba_mm?: number
  meopen_um?: number
  mesh_count?: number
  senkei_um?: number
  kaikouritsu?: number
  zaiko_match?: string
  zaiko_status?: string
}

// User-editable overrides stored in Firestore
export type ProductOverride = {
  shiire_per_m?: number
  kotei_hi?: number
  arari_rate?: number
  updated_at: string // ISO 8601
}

// Search filter
export type SearchFilter = {
  zaishitsu?: string
  meopen_um_min?: number
  meopen_um_max?: number
  mesh_count_min?: number
  mesh_count_max?: number
  senkei_um_min?: number
  senkei_um_max?: number
  kaikouritsu_min?: number
  kaikouritsu_max?: number
  zaiko_haba_mm_min?: number
  zaiko_haba_mm_max?: number
  hinban?: string
  ec_hinban?: string
  color?: string
  freeText?: string
}

// Sort
export type Sort = {
  field: 'hinban' | 'meopen_um' | 'mesh_count' | 'senkei_um' | 'kaikouritsu' | 'zaiko_haba_mm' | 'shiire_per_m' | 'hanbai_kakaku' | 'ec_hinban' | 'zaishitsu'
  order: 'asc' | 'desc'
}

// SearchResult
export type SearchResult = {
  product: UnifiedProduct
  calculatedPrice: number | null
  overridden?: boolean // true if any field has a Firestore override
}

// Pagination
export type Pagination = {
  page: number
  pageSize: number
  totalResults: number
  totalPages: number
}
